---
title: "differential abundances"
format: html
---


```{r}
# Run intro scripts
# source("scripts/01_metadata_import_clean.R") # Run only if changes made to metadata
# source("scripts/02_import_mag_sylph_16s.R")
    load("output/data/mt_16s.RData")
    load("output/data/mt_mag.RData")
    load("output/data/mt_sylph.RData")
```

# Load Required Libraries

```{r}
library(plotly)
library(ggalluvial)
library(ggarrow)
library(tidyverse)
library(microeco)
library(tidytree)
BiocManager::install("ggtree")
library(ggtree)
```

# Create trans_diff object


```{r}
# View sample table 
# view(mt_mag$sample_table)
t1 <- trans_diff$new(dataset = mt_mag, method = "lefse", group = "strat_season", alpha = 0.05, taxa_level = 'all', lefse_subgroup = NULL)
view(t1$res_diff)
t1$plot_diff_cladogram()
t1$plot_diff_bar(threshold = 4.5)
# we show 20 taxa with the highest LDA (log10)
t1$plot_diff_bar(use_number = 1:30, width = 0.8, add_sig = T)


t1 <- trans_diff$new(dataset = mt_mag, method = "lefse", group = "strat_season", alpha = 0.05, taxa_level = 's', lefse_subgroup = NULL)
view(t1$res_diff)

t1$plot_diff_bar(threshold = 4.5)
# we show 20 taxa with the highest LDA (log10)
t1$plot_diff_bar(use_number = 1:30, width = 0.8, add_sig = T)


t1 <- trans_diff$new(dataset = mt_16s, method = "lefse", alpha = 0.1, group = "strat_season", lefse_subgroup = '')

t1$plot_diff_bar(threshold = 4)
# we show 20 taxa with the highest LDA (log10)
t1$plot_diff_bar(use_number = 1:30, width = 0.8)

t1$plot_diff_abund(use_number = 1:20)
t1$plot_diff_abund(use_number = 1:20, fill = "strat_season", alpha = 0.05, add_sig = F)

t1$plot_diff_cladogram()


```

"LEfSe scores can be interpreted as the degree of consistent difference in relative abundance between features in the two classes of analyzed microbial communities." - Segata et al 2011

```{r}
# See if I can quick figure out collinear variables

vifs <- mt_mag$sample_table |> 
    select(where(is.numeric)) |> 
    select(-c(depth, mtemp_2_c_24h_avg, mtemp_c_24h_avg, temp_c_14d_avg)) |> 
    drop_na() |> 
    cor()

corrplot::corrplot(vifs)
table(mt_mag$sample_table$strat_season, mt_mag$sample_table$use_maestro)

```