---
title: "07_gene_abundance"
format: html
---

```{r}
# Install libraries I might need
# BiocManager::install("ANCOMBC")
# BiocManager:: install("ALDEx2")
```
```{r, echo = F}
# Load Libraries
library(microeco)
library(file2meco)
library(tidyverse)
# library(lefser)
library(phyloseq)
library(ANCOMBC)
library(ALDEx2)
library(igraph)
```


# Load Data

```{r}
load("output/data/mt_gene_mag.RData")
```

# Create Trans func and run ancomb

```{r}
# Run this line only if you need to recreate the gene object, it will take a long time. 
# t1 <- trans_diff$new(dataset = mt_gene_mag, method = "ancombc2", group = "strat_season", fix_formula = "strat_season", alpha = 0.05, taxa_level = 'gene')
```

```{r}
view(t1$res_diff)

t2 <- clone(t1)

t2$res_diff$Factors <- t2$res_diff$Factors |> 
    str_replace("\\((i|I)ntercept\\)", "summer") |> 
    str_replace("strat_season.L", "fall") |> 
    str_replace("strat_season.Q", "winter") |> 
    str_replace("strat_season.C", "spring")

sig_taxa <- t2$res_diff |> 
    filter (P.adj <=0.05) |> 
    dplyr::select(Taxa, , Factors, Significance, lfc ) |> 
    separate_wider_delim(Taxa, delim = "|", names = c("bin", "l1", "l2", "l3", "l4", "func", "id")) |> 
    arrange(Factors, -abs(lfc), Significance)

view(sig_taxa)

t3 <- clone(t1)

t3$res_diff$Factors <- t3$res_diff$Factors |> 
    str_replace("\\((i|I)ntercept\\)", "summer") |> 
    str_replace("strat_season.L", "fall") |> 
    str_replace("strat_season.Q", "winter") |> 
    str_replace("strat_season.C", "spring")

t3$res_diff <- t3$res_diff |>  
    dplyr::select(Taxa, Factors, Significance, lfc, P.adj ) |>
    filter(P.adj <= 0.05) |> 
    separate_wider_delim(Taxa, delim = "|", names = c("bin", "l1", "l2", "l3", "l4", "func", "id"))

t3$plot_diff_bar(keep_full_name = TRUE, heatmap_cell = "P.adj", heatmap_sig = "Significance", heatmap_x = "Factors", heatmap_y = "id")

fig_pair <- t2$res_diff |> 
    filter(t2$res_diff$P.adj < 0.05) |> 
    mutate(Taxa = str_remove(Taxa, "\\|WM.*")) |> 
    mutate(Taxa = str_remove(Taxa, "d__Bacteria\\|")) |> 
    mutate(Taxa = str_remove(Taxa, "\\|s__.*")) |> 
    distinct(Taxa, .keep_all = T) |> 
    ggplot(aes(x = Factors, y = Taxa, fill = lfc)) + 
    geom_tile(color = "black") +
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                         na.value = "white",
                         name = NULL) +
    geom_text(aes(Factors, Taxa, label = lfc), size = 5, color = "black") +
    scale_color_identity(guide = FALSE) +
    labs(x = NULL, y = NULL, title = "Gene Log fold changes compared to summer, (p < 0.1)") +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5), text = element_text(color = "black", size = 15))
fig_pair
```

# Run lefse (beware of lots of false positive)

```{r}

t1 <- trans_diff$new(dataset = mt_gene_mag, method = "lefse", group = "strat_season", fix_formula = "strat_season", alpha = 0.05, taxa_level = 'all', p_adjust_method = "none")
view(t1$res_diff)

```

# Try to check out the aldex2 data

```{r}
alde <- clone(mt_gene_mag)
alde$otu_table <- alde$otu_table |> 
    mutate(across(everything(), ~ round(.x * 100000, digits = 0 )))
view(alde$otu_table)


t1 <- trans_diff$new(dataset = alde, method = "ALDEx2_k", group = "strat_season", fix_formula = "strat_season", alpha = 0.05, taxa_level = 'gene')
view(t1$res_diff)

```

# Basic Abundance Graphs

```{r}

taxrank = "gene"
ntaxa = 1

t1 <- clone(mt_gene_mag)
t1$tax_table <- t1$tax_table |> 
    filter(gene == "K06034")

t1$tidy_dataset()
view(t1$otu_table)

plot <- trans_abund$new(t1, taxrank = taxrank, ntaxa = ntaxa)$
    plot_bar(facet = "strat_season")
plot
```
```{r, echo = F}
# Load in data
#FOAM data
foam_1_df <- read_tsv("output/data/metabolism/foam_1.tsv")
foam_2_df <- read_tsv("output/data/metabolism/foam_2.tsv")
foam_3_df <- read_tsv("output/data/metabolism/foam_3.tsv")
foam_id_df <- read_tsv("output/data/metabolism/foam_genes.tsv")
# KEGG data (more genes total)
kegg_1_df <- read_tsv("output/data/metabolism/kegg_1.tsv")
kegg_2_df <- read_tsv("output/data/metabolism/kegg_2.tsv")
kegg_3_df <- read_tsv("output/data/metabolism/kegg_3.tsv")
kegg_id_df <- read_tsv("output/data/metabolism/kegg_genes.tsv")
```

``` {r, echo = F}
# Load in the microtable objects
load("output/data/mt_mag.RData")
load("output/data/mt_16s.RData")
```

```{r}
# Try to make a new microtable object, might need to do some work to get it into a human readable format

foam_1_wide <- foam_1_df |> 
    # mutate(bin = str_extract(bin, "^.{4}")) |> 
    pivot_wider(names_from = name, values_from = count) |> 
        column_to_rownames("bin")

foam_mt <- microtable$new(otu_table = foam_1_wide, sample_table = mt_mag$sample_table, tax_table = mt_mag$tax_table)

foam_mt$cal_abund(rel = FALSE)
# use_percentage = FALSE disable percentage for relative abundance
test1 <- trans_abund$new(test, taxrank = "Level.2", ntaxa = 10, use_percentage = FALSE)
test1$plot_bar(facet = "Group", bar_full = FALSE, xtext_angle = 30) + ggplot2::ylab("Abundance (RPK)")

# Now that we have a wide df, try to plot it

foam_1_df |> 
    group_by(bin) |> 
    mutate(rel_abund = count/sum(count)) |> 
    ungroup() |> 
    ggplot(aes(x = bin, y = rel_abund, fill = name)) +
    geom_bar(stat = "identity")

#

```

```{r}
# Code from the tutorial
library(microeco)
library(file2meco)
library(magrittr)
?humann2meco
sample_file_path <- system.file("extdata", "example_metagenome_sample_info.tsv", package="file2meco") |> 
    read_tsv()
match_file_path <- system.file("extdata", "example_metagenome_match_table.tsv", package="file2meco") |> 
    read_tsv()
# use KEGG pathway based HUMAnN result
abund_file_path <- system.file("extdata", "example_HUMAnN_KEGG_abund.tsv", package="file2meco") |> 
    read_tsv() |> 
    separate_wider_delim("# Pathway", names = c("gene", "org"), delim = "|", too_few = "align_start")
# match_table parameter can be used to replace sample names
test <- humann2meco(abund_file_path, db = "KEGG", sample_table = sample_file_path, match_table = match_file_path)
# remove the unclassified pathway in Level.1
test$tax_table %<>% subset(Level.1 != "unclassified")
test$tidy_dataset()
# rel = FALSE donot use relative abundance, use the raw RPK
test$cal_abund(select_cols = 1:3, rel = FALSE)
# use_percentage = FALSE disable percentage for relative abundance
test1 <- trans_abund$new(test, taxrank = "Level.2", ntaxa = 10, use_percentage = FALSE)
test1$plot_bar(facet = "Group", bar_full = FALSE, xtext_angle = 30) + ggplot2::ylab("Abundance (RPK)")

tax_test <- test$tax_table |> 
    rownames_to_column("gene_name") |> 
    mutate(gene_simp = str_extract(gene_name, "^.{7}"))


```


Sample Table:

OTU table: Rows are the individuals columns are the samples (WM01 - WM24)

Tax table: added columns (level 1, 2, 3) for each of the kegg levels in front of the typical kingdom phylum class data, rows are each individual. 
```{r}
# Test
abund_file_path <- system.file("extdata", "example_HUMAnN_KEGG_abund.tsv", package="file2meco")
abund_file_path <- system.file("extdata", "example_Ncyc_table.tsv", package="file2meco")
test <- read_tsv(abund_file_path)
```


```{r}
# Figure out how many are in each group

foam_1_df <- foam_1_df |> 
    group_by(bin) |> 
    mutate(n = length(unique(name))) |> 
    ungroup()
```


```{r}
# New test to see how the rollup files work

foam_df <- read_tsv("output/data/metabolism/foam_rollup.tsv")
# foam_df <- read_tsv("output/data/metabolism/foam_rollup_all.tsv")
load("output/data/mt_mag.RData")

# Cut down the foam_df to only include bins that are in the mag dataset
foam_df_cut <- foam_rollup_df |> 
    slice(which(foam_rollup_df$bin %in% rownames(mt_mag$tax_table)))

# Isolate just the nitrogen cycle genes
foam_df_cut <- foam_df_cut |> 
    mutate(rowname = paste0(id, "|", bin)) |> 
    relocate(rowname) |> 
    filter(l1 == "11_Nitrogen cycle") |> 
    arrange(bin, rowname, l1, l2) |> 
    distinct()

 repeats <- foam_df_cut |>
  dplyr::summarise(n = dplyr::n(), .by = c(rowname, bin, l1)) |>
  dplyr::filter(n > 1L)

foam_df_cut <- foam_df_cut |> 
slice(-which(foam_df_cut$rowname == repeats$rowname[1])[2])

 repeats <- foam_df_cut |>
  dplyr::summarise(n = dplyr::n(), .by = c(rowname, bin, l1)) |>
  dplyr::filter(n > 1L)


# Okay no repeats, now see if I can make another table

foam_cut_wide <- foam_df_cut |>
    dplyr::select(-matches(c("func", "l1", "count", "id", "ec"))) |> 
    pivot_wider(names_from = l2, values_from = c(l3, l4)) |> 
    dplyr::select(-bin) |> 
    column_to_rownames("rowname") |> 
    filter(!if_all(everything(), is.na)) |> 
    rownames_to_column("rowname") |> 
    separate_wider_delim("rowname", delim = "|", names = c("id", "bin")) |> 
    dplyr::select(-id) |> 

    

colnames_change <- colnames(foam_cut_wide) |> 
    str_which(".*\\_.*") 
prefix <- c("l3", "l4", "id", "ec")

for(i in 1:length(prefix)){
foam_cut_wide <- foam_cut_wide |> 
    rename_with(~paste0(str_remove(.x, prefix[i]),"_", prefix[i]), 
    starts_with(prefix[i]))
}
foam_cut_wide <- foam_cut_wide |> 
    rename_with(~str_remove(.x, "^\\_"), starts_with("\\_"))



# How many distinct l1s do we have?

lvl1_cols <- foam_df_cut$l1 |> 
    unique() |> 
    sort()

info <- seq(01:21)
info <- paste0(info, "_info")
info <- stringr::str_pad(info, 7, side = "left", pad = "0")
info

colnames <- c(lvl1_cols, info) |> 
    sort()

# Create blank data frame
new_df <- data.frame(matrix(nrow = nrow(mt_mag$tax_table), ncol = length(colnames) + 1))
colnames(new_df) <- c("bin", colnames)

new_df <- new_df |> 
    mutate(bin = unique(foam_df_cut$bin))
for(i in 1:length(lvl1_cols)) {

}


test <- clone(mt_mag)


lvl2_cols <- foam_df_cut$l2 |> 
    unique()
# Check for repeat rownames
nrow(foam_df_cut) == length(unique(foam_df_cut$rowname))

# There are repeat rownames, likely due to functional redundancies. I need to next look at which pathway to put them in and how to deal with the additional counts of the gene. 


# Only keep the first of the rownames
foam_df_test <- foam_df_cut |> 
    # group_by(rowname) |> 
    # mutate(tot_count = sum(count)) |> 
    # ungroup() |> 
    # mutate(count = count_sum,
    # -count_sum) |> 
        distinct(rowname, .keep_all = T)

nrow(foam_df_test)

# Now append all the additional taxa data into the table

# waldo::compare(core_bins, rownames(mt_mag$tax_table))

# core_bins <- sort(core_bins)
mag_names <- sort(rownames(mt_mag$tax_table))
tax_test <- mt_mag$tax_table |> 
    rownames_to_column("bin") |> 
    left_join(y = foam_df_test, by = "bin") |> 
    column_to_rownames("rowname")

# Make an otu_table 

otu_table <- mt_mag$otu_table |> 
    rownames_to_column("bin")

tax_names <- tax_test |> 
    rownames_to_column("rowname") |> 
    dplyr::select(rowname, bin)

otu_table_final <- otu_table |> 
    left_join(tax_names) |> 
    dplyr::select(-bin) |> 
    column_to_rownames("rowname")


mt_genes <- microeco::microtable$new(tax_table = tax_test, otu_table = otu_table_final, sample_table = mt_mag$sample_table)

mt_genes$cal_abund()
    t1 <- trans_diff$new(mt_genes, method = "lefse", group = "strat_season", p_adjust_method = "none")
    save(t1, "output/data/metabolism/t1.RData")
    t1$plot_diff_bar(threshold = 2.5)


test$tax_table <- test$tax_table |> 
    subset()

test$tidy_dataset()
t1 <- trans_abund$new(test, taxrank = "l2", ntaxa = 10, use_percentage = FALSE)
trans_abund$plot_bar(t1, facet = "strat_season", bar_full = FALSE, xtext_angle = 30) + ggplot2::ylab("Abundance (RPK)")

```

# Test
```{r}
# Load required libraries
library(microeco)
library(magrittr)

# -------------------------------------------------------------------
# STEP 1: Extract data from your existing bin microtable
# -------------------------------------------------------------------
# Assuming your existing microtable is named 'mt_mag'
bin_abund <- mt_mag$otu_table
sample_meta <- mt_mag$sample_table


# -------------------------------------------------------------------
# STEP 2: Prepare the FOAM gene table
# -------------------------------------------------------------------
# Assuming 'foam_genes' is your loaded data.frame where:
# - Rownames are FOAM gene IDs (e.g., "FOAM_0001")
# - Colnames are Bin IDs (must match the rownames of bin_abund)
# - Values are gene copy numbers (or 1/0 for presence/absence)


foam_table <- foam_df_cut |> 
    group_by(bin, id) |> 
    tally(count)
foam_table |> 
ggplot(aes(x = n)) +
geom_histogram()

# Okay it looks like there are not really many issues where need to worry about there being more than 1 gene copy.

foam_table_wide <- foam_table |> 
    pivot_wider(names_from = bin, values_from = n) |> 
    column_to_rownames("id") |> 
    # Make it a presence abesnce thing (change things here if I need to)
    mutate(across(everything(), ~ifelse(is.na(.x), 0, 1)))

# -------------------------------------------------------------------
# STEP 3: Calculate Gene Abundances across samples
# -------------------------------------------------------------------
# Matrix multiplication: 
# (Genes x Bins matrix) %*% (Bins x Samples matrix) = (Genes x Samples matrix)
gene_abund_matrix <- as.matrix(foam_table_wide) %*% as.matrix(bin_abund)

# Convert back to a dataframe for the microtable
gene_abund <- as.data.frame(gene_abund_matrix)


# Create a tax_table, but only keep one of the l1, l2, l3 explanations. Here we are losing some information about what gene pathways genes are being used for. 

tax_table <- foam_df_cut |> 
    select(bin, id, l1, l2, l3, l4, `function`) |> 
    distinct() |> 
    group_by(id) |> 
    slice_head() |> 
    mutate(gene = id) |> 
    column_to_rownames("id")


# -------------------------------------------------------------------
# STEP 4: Create the new FOAM Gene microtable
# -------------------------------------------------------------------
# Instantiate a new microtable where the "OTUs" are now your FOAM genes
mt_genes_mag <- microtable$new(otu_table = gene_abund, 
                             sample_table = sample_meta, 
                             tax_table = tax_table)

# Optional but highly recommended: If you have a functional hierarchy/taxonomy 
# for your FOAM genes (e.g., Level 1, Level 2, Gene), add it as the tax_table!
# meco_genes$tax_table <- foam_hierarchy_df

# Clean the dataset to remove any genes that have 0 abundance across all samples
mt_genes_mag$tidy_dataset()

# -------------------------------------------------------------------
# STEP 5: Run Differential Abundance
# -------------------------------------------------------------------
# Now you can use trans_diff on the genes just like you would on taxonomy.
# Replace "YourGroupColumn" with the actual column name in your sample_table.

# Example using LEfSe (Linear discriminant analysis Effect Size)
t_diff <- trans_diff$new(dataset = mt_genes_mag, 
                         method = "ancombc2", 
                         group = "strat_season", 
                         alpha = 0.05)

# View the results
head(t_diff$res_diff)

# Plot the top 20 differentially abundant genes
t_diff$plot_diff_bar(use_number = 1:20)
```