---
title: "Initial Explorations"
format: html
editor: visual
---

# Load required packages

```{r}
library(tidyverse) 
library(vegan) 
library(Polychrome) 
library(forcats)
library(paletteer)
library(ggarrow)
```

# Read in the data

```{r}

b_df <- readr::read_tsv("data/superior_sylph/Sylph_TaxAbund_out.tsv")
```

# Clean data

```{r}

# Create vectors of column names
clade_cols <- stringr::str_extract_all(b_df$clade_name[8], "[a-z]{1}(?=_)")

clade_cols <- as.vector(clade_cols[[1]]) %>% print()

site_cols <- 
  stringr::str_extract(colnames(b_df), "(?<=/).{4}") %>%   
  na.omit() %>% 
  print() 

colnames(b_df)[2:ncol(b_df)] <- site_cols

#Spread columns out, clean names

b_df <- b_df %>% tidyr::separate_wider_delim(cols = clade_name, delim = "|", names = clade_cols, too_few = "align_start") %>% 
  # Drop all rows that don't get down to a taxa 
  tidyr::drop_na("t") %>%
  #remove additional characters and make data columns numeric
  mutate(across(clade_cols, ~ str_remove(., "[a-z]__")))

# Quick check to see if abundances are all still 100 
colSums(b_df[9:ncol(b_df)])

# Load metadata
sw_meta <- read_csv("data/sw_metadata.csv")

#Create long df 
long_b_df <- b_df %>% pivot_longer(cols = all_of(site_cols), names_to = "sample", values_to = "abundance")

long_b_df <- long_b_df %>% 
  mutate(date = sw_meta$date[match(long_b_df$sample, sw_meta$Sample)]
  )
long_b_df$date <- mdy(long_b_df$date)


```

# Plots

## Other dfs to examine

```{r}
bacter_df <- long_b_df %>% 
  filter(p == "Bacteroidota") %>% 
  group_by(date, abundance)


palette <- length(unique(bacter_df$f)) %>% glasbey.colors() %>% unname()

test_bar_bacter <-
bacter_df %>% 
  ggplot(aes(x = sample, y = abundance, fill = f)) + 
  geom_bar(stat = "identity") + 
  # scale_fill_discrete() +
  scale_fill_manual(values = palette)+
  scale_x_discrete(
                   labels = as.character(format(long_b_df$date, "%m-%d"))
                   )+
  labs(x = "Date", y = "Abundance", legend = "Phyla", fill = "Phyla") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9)) +
  NULL

test_bar_bacter

bacter_df <- long_b_df %>% 
  filter(p == "Actinomycetota") %>% 
  group_by(date, abundance)


# palette <- length(unique(bacter_df$f)) %>% glasbey.colors() %>% unname()

test_bar_act <-
bacter_df %>% 
  ggplot(aes(x = sample, y = abundance, fill = f)) + 
  geom_bar(stat = "identity") + 
  scale_fill_discrete() +
  # scale_fill_manual(values = palette)+
  scale_x_discrete(
                   labels = as.character(format(long_b_df$date, "%m-%d"))
                   )+
  labs(x = "Date", y = "Abundance", legend = "Phyla", fill = "Phyla") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9)) +
  NULL

test_bar_act


bacter_df <- long_b_df %>% 
  filter(p == "Pseudomonadota", 
         abundance > 0.1) %>% 
  group_by(date, abundance)


palette <- length(unique(bacter_df$f)) %>% glasbey.colors() %>% unname()

test_bar_pseudo <-
bacter_df %>% 
  ggplot(aes(x = sample, y = abundance, fill = f)) + 
  geom_bar(stat = "identity") + 
  # scale_fill_discrete() +
  scale_fill_manual(values = palette)+
  scale_x_discrete(
                   labels = as.character(format(long_b_df$date, "%m-%d"))
                   )+
  labs(x = "Date", y = "Abundance", legend = "Phyla", fill = "Phyla") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9)) +
  NULL

test_bar_pseudo
```

## Bar chart

```{r}
#First create a unique palette based on how many categories there are 
palette <- length(unique(bacter_df$p)) %>% glasbey.colors() %>% unname()

long_b_df$p <- fct_reorder(long_b_df$p, long_b_df$abundance)

# Plot
phyla_bar_date <-
long_b_df %>% 
filter(abundance > 0.2) |> 
  ggplot(aes(x = sample, y = abundance, fill = p)) + 
  geom_bar(stat = "identity") + 
  # scale_fill_discrete() +
  scale_fill_manual(values = palette)+
  scale_x_discrete(
                   labels = as.character(format(long_b_df$date, "%m-%d"))
                   )+
  labs(x = "Date", y = "Abundance", legend = "Phyla", fill = "Phyla") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9)) +
  NULL

phyla_bar_date

ggsave("output/phyla_abund_date.jpg", plot = phyla_bar_date)


phyla_bar_sample <-long_b_df %>% ggplot(aes(x = sample, y = abundance, fill = p)) + geom_bar(stat = "identity") + 
  # scale_fill_discrete() +
  scale_fill_manual(values = palette)+
  scale_x_discrete() +
  labs(x = "Sample", y = "Abundance", legend = "Phyla", fill = "Phyla") + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9)) +
  NULL 

phyla_bar_sample

ggsave("output/phyla_abund_sample.jpg", phyla_bar_sample)
```

## Class chart

Only of 5 major families

```{r}
# Plot

long_b_df %>% 
  filter(p == c("Pseudomonadota", "Bacteriodita", "Actinomycetota", "Planctomycetota", "Verrucomicrobiota"), abundance > 0.1) %>%
           ggplot(aes(x = sample, y = abundance, fill = fct_reorder(f, abundance)))+ 
  geom_bar(stat = "identity", position = position_fill()) + 
  # scale_fill_discrete() +
  # scale_fill_manual(values = palette)+
  scale_color_paletteer_d() +
  scale_x_discrete(guide = guide_axis(n.dodge = 2)) +
  NULL
```

## NMDS

```{r}
# NMDS model

nmds <- b_df %>% 
  select(all_of(site_cols)) %>% 
  t() %>% 
  # decostand("hellinger") %>% 
  metaMDS(distance="bray", autotransform=FALSE, binary=FALSE, noshare=TRUE, zerodist="ignore")

# Extract scores

nmds_scores <- scores(nmds, display = "sites") %>% 
  data.frame() %>%
  rownames_to_column(var = "sample") %>% 
  mutate(
    samp_num = as.numeric(
      str_extract_all(nmds_scores$sample, "[0-9]{2}"))
      )

lab_data <- nmds_scores %>% 
  filter(samp_num  %in% c(1, 5, 16, 24))
# Basic NMDS plot 
nmds_basic_plot <- 
  ggplot(nmds_scores, aes(x = NMDS1, y = NMDS2, color = as.numeric(samp_num))) +
  geom_point(size = 3, alpha = 0.8) + 
  geom_text(
    data = lab_data, # Filter data for the label layer
    aes(label = sample),
    vjust = -1.1, # Adjust vertical position
    hjust = 0.5,  # Adjust horizontal position
    color = "black"
  ) +
  geom_arrow_chain(colour = "black") +
  scale_color_viridis_b()  +
  labs(title = "NMDS Ordination of WM Data", subtitle = paste("Stress =",      round(nmds$stress, 3)), x = "NMDS1", y = "NMDS2", color = "Sample") +
  guides(color = "none") +
  theme_classic()

nmds_basic_plot

ggsave(plot = nmds_basic_plot,filename = "output/sup_winter_nmds.jpg")

# Run stressplot 
stressplot(nmds)

```

##