---
title: "Untitled"
format: html
---

# Load Libraries
```{r}
library(tidyverse)
library(microeco)
# For importing .biom file
library(phyloseq)
library(file2meco)
# Extra packages for plotting
library(ggalluvial)
library(ggnested) # Needs to be installed from github not CRAN
library(ggarrow)
library(plotly) # for interactive plots
```

```{r}
source("scripts/01_intro_script.R")
```
# Read in the data

```{r}

b_df <- readr::read_tsv("data/superior_sylph/Sylph_TaxAbund_out.tsv")
```

# Clean data

```{r}

# Create vectors of column names
clade_cols <- stringr::str_extract_all(b_df$clade_name[8], "[a-z]{1}(?=_)")

clade_cols <- as.vector(clade_cols[[1]]) %>% print()

site_cols <- 
  stringr::str_extract(colnames(b_df), "(?<=/).{4}") %>%   
  na.omit() %>% 
  print() 

colnames(b_df)[2:ncol(b_df)] <- site_cols

#Spread columns out, clean names

b_df <- b_df %>% tidyr::separate_wider_delim(cols = clade_name, delim = "|", names = clade_cols, too_few = "align_start") %>% 
  # Drop all rows that don't get down to a taxa 
  tidyr::drop_na("t") %>%
  #remove additional characters and make data columns numeric
  mutate(across(clade_cols, ~ str_remove(., "[a-z]__")))

# Quick check to see if abundances are all still 100 
colSums(b_df[9:ncol(b_df)])

# Load metadata
sw_meta <- read_csv("data/sw_metadata.csv")

#Create long df 
long_b_df <- b_df %>% pivot_longer(cols = all_of(site_cols), names_to = "sample", values_to = "abundance")

long_b_df <- long_b_df %>% 
  mutate(date = sw_meta$date[match(long_b_df$sample, sw_meta$Sample)]
  )
long_b_df$date <- mdy(long_b_df$date)


```

# Create New microtable object


```{r}

otu_table <- b_df |> 
    rownames_to_column("otu") |> 
    select(all_of(site_cols), "otu") |> 
    column_to_rownames("otu") |> 
    as.data.frame()

tax_table <- b_df |> 
    rownames_to_column("otu") |> 
    select(all_of(clade_cols), "otu") |> 
    column_to_rownames("otu") |> 
    as.data.frame()

sample_table <- sw_meta |> 
    column_to_rownames("Sample") |> 
    as.data.frame()

mt <-microtable$new(otu_table = otu_table, sample_table = sample_table, tax_table = tax_table)

mt$tidy_dataset()

```

# Calculations

```{r}
# Calculate relative abunance
mt$cal_abund()
mt$taxa_abund$p[1:5,1:5]

# Calc Alpha Diversity
mt$cal_alphadiv()

# Calc Bray Curtis Dissimilarity
mt$cal_betadiv()
mt$beta_diversity$bray
```

# Abundance Plots
```{r}

# Set rank (k, p, c, etc) and number of taxa to include
rank <- "f"
n <- 20

# Create abundance object
ts1 <- trans_abund$new(mt_sylph, taxrank = rank, ntaxa = n)

# Plot abunances
ts1 <- mt_sylph |>
  filter(.$tax_table, f == "Chitinophagaceae") |>
   trans_abund$new(mt_sylph, taxrank = rank, ntaxa = n)
ts1$plot_bar(others_color = "grey70", xtext_keep = TRUE, legend_text_italic = FALSE) |> 
  ggplotly()
ts1$plot_bar(others_color = "grey70", xtext_keep = TRUE, legend_text_italic = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9)) |> 
  ggplotly()

# Plot alluvial

ts1$plot_bar(bar_full = F, use_alluvium = T, others_color = "grey70", xtext_keep = TRUE, legend_text_italic = FALSE, clustering = T) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9))

# Double Abudances plot
  # Sylph data
ts2 <- trans_abund$new(dataset = mt_sylph, taxrank = "f", ntaxa = 20)
#  show = 0, high_level = "p", high_level_fix_nsub = 2)

ts2$plot_bar(ggnested = F, xtext_angle = 45) |> 
    ggplotly()
    # 16S data
  t2 <- trans_abund$new(dataset = meco_16s, taxrank = "f", ntaxa = 20, show = 0, high_level = "p", high_level_fix_nsub = 6)

t2$plot_bar(ggnested = T, xtext_angle = 45) +
    ggtitle("16S") |> 
    ggplotly()

# Heat Map

t3 <- trans_abund$new(dataset = mt, taxrank = "g", ntaxa = 40)
g1 <- t3$plot_heatmap(xtext_keep = T, withmargin = FALSE, plot_breaks = c(0.01, 0.1, 1, 10))
g1
g1 + theme(axis.text.y = element_text(face = 'italic'), axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size=9))
```

# Alpha Diversity

```{r}

mt_sylph$alpha_diversity |>
  rownames_to_column("sample") |> 
  ggplot(aes(sample, Simpson, group = 1)) +
  geom_point() +
  geom_line() +
  geom_line(data = sw_meta, aes(sample, temp_c_24h_avg))
```

# Beta Diversity

```{r}
tb2 <- trans_beta$new(mt_sylph, group = "strat_season", measure = "bray")
tb2$cal_ordination(method = "NMDS")

tb2$plot_ordination(plot_color = "strat_season", plot_shape = "strat_season", plot_type = c("point", "ellipse")) +
  #   geom_text(
  #   data = tb2$dataset$otu_table, # Filter data for the label layer
  #   aes(label = sample),
  #   vjust = -1.1, # Adjust vertical position
  #   hjust = 0.5,  # Adjust horizontal position
  #   color = "black"
  # ) +
  # geom_arrow_chain(colour = "black") + 
    ggtitle("Sylph NMDS") +
  # scale_color_viridis_b() +
  NULL

  tb2 <- trans_beta$new(meco_16s, group = "strat_season", measure = "bray")
tb2$cal_ordination(method = "NMDS")

tb2$plot_ordination(plot_color = "strat_season", plot_shape = "strat_season", plot_type = c("point", "ellipse")) +
  # geom_arrow_chain(colour = "black") + 
    ggtitle("16s NMDS") +
  # scale_color_viridis_b() +
  NULL
```

# Figure out which taxa are shared between the 16s and metagenomic data


```{r}
 # Sylph data

tax_rank <- "f"
ntaxa <- 20
 ts2 <- trans_abund$new(dataset = mt_sylph, taxrank = tax_rank, ntaxa = ntaxa, delete_taxonomy_lineage = T, show = 0.01, high_level = "p", high_level_fix_nsub = 10)

ts2$plot_bar(ggnested = F, xtext_angle = 45, color_values = RColorBrewer::brewer.pal(15, "Dark2"))

  # 16s data

  t2 <- trans_abund$new(dataset = meco_16s, taxrank = tax_rank, ntaxa = ntaxa)
  #  show = 0, high_level = "", high_level_fix_nsub = 20)

compare_df <- data.frame("16s" = t2$data_taxanames, "sylph" = ts2$data_taxanames)
compare_df$X16s[compare_df$X16s %in% compare_df$sylph]
t2$plot_bar(ggnested = F, xtext_angle = 45) +
  ggtitle("16S", subtitle = "20 most abundant families")

test_df <- b_df |> 
  rowwise() |> 
  mutate(
    mean_abund = mean(c_across(all_of(site_cols)))
  ) |> 
    ungroup() |> 
    filter(f == "Microbacteriaceae")
    
  # select(all_of(site_cols)) |> 
  # mutate(mean_abund = rowMeans(select(all_of(site_cols))))
```


```{r}
# Create folder directory for sylph data
for(taxa in 1:nrow(mt$tax_table)) {
# Create a way to make the filepath
 path <- mt$tax_table |> 
  slice(taxa)
# Create the file path
do.call(file.path, as.list(path)) |> 
  dir.create(recursive = T)
}
```

# Plot just a single taxa abundance


```{r}
# Clone dataset
taxa <- "Sphingomonadaceae"
mt_sylph_subset <- clone(mt_sylph)

###mt_sylph_subset
mt_sylph_subset$tax_table <- mt_sylph_subset$tax_table |> 
  filter(f == taxa)
mt_sylph_subset$tidy_dataset()

# check
mt_sylph_subset # OK
head(mt_sylph_subset$tax_table)

# recalculate abundances (needed?)
mt_sylph_subset$cal_abund()
mt_sylph_subset$taxa_abund

# plot:
t1 <- trans_abund$new(dataset = mt_sylph_subset, taxrank = "s", ntaxa = 10)
t1$plot_bar() |> ggplotly()
```